### ISSUE TITLE
Typo in Chapter 4

### ISSUE THREAD

**Issue by azza-bouleimen** [CrumpLab/statistics#6]
Hello, I think there is typo in Chapter 4 that would be important to fix since it completely changes the meaning of the sentence.
I section 4.1, the sentence "So that’s probability. What about statistics? Statistical questions work the other way around. In statistics, we **_know_** the truth about the world." should be, if I understood things right,  "So that’s probability. What about statistics? Statistical questions work the other way around. In statistics, we **_do not know_** the truth about the world. "

**Comment by CrumpLab** [comment]
Thanks for catching this, should be fixed now.
